### ISSUE TITLE
errors during npm install on clean machine

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#135]
On a clean machine I tried to get monterey running (clone, npm install then gulp watch)

First it threw an error about python not being installed, so I installed python (must be 2.7, not 3.0). Had to tick the checkbox to add python to the PATH variable

Then it gave me this:
``` 
Installing app dependencies for arch x64 to C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app


> nslog@3.0.0 install C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog
> node-gyp rebuild


C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
monterey@0.2.2 C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\npm-debug.log
npm ERR! code 1
Unhandled rejection Error: C:\Program Files\nodejs\node.exe exited with code 1
    at ChildProcess.childProcess.on.code (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:137:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:112:9)
    at spawnNpmProduction (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:46:9)
    at Object.installDependencies (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:24:120)
    at C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:29:2
    at next (native)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at tsAwaiter (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:22:3)
    at Object.<anonymous> (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:34:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
``` 

From the node-gyp README I saw that I needed to run `npm install --global --production windows-build-tools`

Afterwards the error changed into:

``` 
C:\Users\Jeroen\Downloads\monterey-master\monterey-master>npm install

> monterey@0.2.2 postinstall C:\Users\Jeroen\Downloads\monterey-master\monterey-master
> install-app-deps

Installing app dependencies for arch x64 to C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app


> nslog@3.0.0 install C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog
> node-gyp rebuild


C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_m
odules\nslog\build\nslog.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
monterey@0.2.2 C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\npm-debug.log
npm ERR! code 1
Unhandled rejection Error: C:\Program Files\nodejs\node.exe exited with code 1
    at ChildProcess.childProcess.on.code (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:137:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:112:9)
    at spawnNpmProduction (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:46:9)
    at Object.installDependencies (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:24:120)
    at C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:29:2
    at next (native)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at tsAwaiter (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:22:3)
    at Object.<anonymous> (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:34:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Comment by JeroenVinke** [comment]
remembered I needed npm@next: `npm install npm@next -g`:

```
> monterey@0.2.2 postinstall C:\Users\Jeroen\Downloads\monterey-master\monterey-master
> install-app-deps

Installing app dependencies for arch x64 to C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app


> nslog@3.0.0 install C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog
> node-gyp rebuild


C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  nslog_win.cc
  win_delay_load_hook.cc
     Creating library C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog\build\Release\ns
  log.lib and object C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog\build\Release\nsl
  og.exp
  Generating code
  Finished generating code
  nslog.vcxproj -> C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog\build\Release\\nslo
  g.node
  nslog.vcxproj -> C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\nslog\build\Release\nslog
  .pdb (Full PDB)

> monterey@0.2.2 postinstall C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app
> electron-rebuild -f -p -w pty.js

Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding
Bad argument
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:372:9)
    at C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\electron-rebuild\lib\spawn.js:28:43
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\core-js\library\modules\$.export.js:30:36)
    at exports.default (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\electron-rebuild\lib\spawn.js:25:10)
    at getElectronModuleVersion$ (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\electron-rebuild\lib\main.js:126:65)
    at tryCatch (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\node_modules\babel-runtime\regenerator\runtime.js:105:21)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jeroen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! monterey@0.2.2 postinstall: `electron-rebuild -f -p -w pty.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the monterey@0.2.2 postinstall script 'electron-rebuild -f -p -w pty.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the monterey package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild -f -p -w pty.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs monterey
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls monterey
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jeroen\Downloads\monterey-master\monterey-master\app\npm-debug.log
Unhandled rejection Error: C:\Program Files\nodejs\node.exe exited with code 1
    at ChildProcess.childProcess.on.code (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:137:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:112:9)
    at spawnNpmProduction (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:46:9)
    at Object.installDependencies (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\util.ts:24:120)
    at C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:29:2
    at next (native)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at tsAwaiter (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:22:3)
    at Object.<anonymous> (C:\Users\Jeroen\Downloads\monterey-master\monterey-master\node_modules\electron-builder\src\install-app-deps.ts:34:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-osx:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-osx@1.0.0
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

changed `./node_modules/.bin/electron-rebuild -f -p -w pty.js` to `./node_modules/.bin/electron-rebuild -f -w pty.js`

this finally allows `npm install`  to finish

**Comment by JeroenVinke** [comment]
so if we're keeping node-gyp the new setup instructions are;

```
npm install --global --production windows-build-tools npm@next
npm install
cd app
jspm install
```

**Comment by vegarringdal** [comment]
Look like a lot like the ```npm -g install npm@next``` I potsed in team chat few days ago.
Think I found is somewhere in visual studio forum, after a update to visual studio community you had to run the latest for compiling native sources on windows
Was driving me crazy there for a while

**Comment by JeroenVinke** [comment]
fixed by @vegarringdal
