### ISSUE TITLE
Aurelia-CLI Default-ESNext fails again

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#209]
The trail of events leading to this problem is documented in the [user manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/Aurelia-CLI/default-esnext.html) - transition from Image 5 to Image 6

The "error warning" button in the footer shows:

![image](https://cloud.githubusercontent.com/assets/2712405/17977985/de1c66ee-6ac1-11e6-8d3b-ca9f7c661502.png)

Clipboard content:

```
TypeError: Cannot read property 'command' of undefined
    at CommandService.runCommand (file:///C:/work/monterey-framework/monterey/app/dist/plugins/aurelia-cli/command-service.js:21:75)
    at file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-manager/command-runner.js:44:34
    at CommandRunner.<anonymous> (file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-manager/command-runner.js:78:67)
    at next (<anonymous>)
    at fulfilled (file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-manager/command-runner.js:13:58)
```

Log file (remove the last postfix "txt" which is added to be able to paste it here)

[2016-08-25.csv.txt](https://github.com/monterey-framework/monterey/files/437585/2016-08-25.csv.txt)

***It seems that it is a bit premature to pursue the plan I wanted to use today - to write User Manual in parallel with testing***.

**Comment by adriatic** [comment]
Confirmed fixed:

![image](https://cloud.githubusercontent.com/assets/2712405/17981729/dea01654-6ad2-11e6-931b-b2fee1ce8171.png)
