### ISSUE TITLE
Skeleton-Esnext-Aspnetcore fails in `gulp watch` step

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#213]
Clipboard content

```
Error: Cannot find module 'skeleton-esnext-aspnetcore\src\skeleton\node_modules\jspm\api.js'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (C:\work\monterey-framework\monterey\node_modules\electron-prebuilt\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.exports.getJSPMModule (C:\work\monterey-framework\monterey\app\jspm_packages\github\monterey-framework\monterey-pal-electron@0.1.41\jspm_commands.js:50:10)
    at Object.exports.install (C:\work\monterey-framework\monterey\app\jspm_packages\github\monterey-framework\monterey-pal-electron@0.1.41\jspm_commands.js:15:22)
    at C:\work\monterey-framework\monterey\app\node_modules\electron-remote\lib\execute-js-func.js:51:21
    at next (<anonymous>)
    at step (C:\work\monterey-framework\monterey\app\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
```

**Comment by adriatic** [comment]
### Update

Trying to run JSPM tile **afterwards**, I realized that JSPM fails as well:

![image](https://cloud.githubusercontent.com/assets/2712405/17992890/0f184c70-6b19-11e6-9b1e-98f7d8320b29.png)

**Finally**: despite having provided GitHub credentials a few hours back working on the [Aurelia-CLI custom](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/Aurelia-CLI/custom.html) section, I was asked to provide these credentials again - and that is the same running instance of Monterey.

**Comment by JeroenVinke** [comment]
Here is my run: ![image](https://cloud.githubusercontent.com/assets/2189477/17996571/0a33c832-6b6a-11e6-938c-256086853518.png)

NPM install took 953 seconds for me, where the timeout of electron-remote is 1000 seconds. So if I needed to guess then i'd say that electron-remote killed the `npm install` process after 1000 seconds, causing that file (`aspnetcore/src/skeleton/node_modules/jspm/api.js`) not to be there, which gave you the error

I have increased the timeout: https://github.com/monterey-framework/monterey/commit/70ffe0f109a76fcc41688711b9e33483b3aea3e1. Can you pull, run `npm install electron-remote` from the app directory and make sure it says that "electron-remote@0.5.12" was installed?

**Comment by adriatic** [comment]
God created a solid continent in less than 953 seconds - so something is not right here. I will repeat this `npm install` (knowing that you increased the limit (why is there a limit, by the way?)) and check the time it took.

I will also run this same project "directly" with Aurelia-CLI to see how much time `npm install` takes without having Monterey in the loop. I suspect that more than 500 seconds is spent by the terminal spewing the useless information. If I am right this will be another reason to review https://github.com/monterey-framework/monterey/issues/198

**Comment by adriatic** [comment]
> NPM install took 953 seconds for me, where the timeout of electron-remote is 1000 seconds

Just did the same run started from Cmder console (renamed the folder node_modules to node_modules-orig first). Here is the time `npm install` took:

![image](https://cloud.githubusercontent.com/assets/2712405/18008167/0a412210-6b75-11e6-9e87-562772b93eeb.png)

**Comment by adriatic** [comment]
The same task executed by Monterey:

![image](https://cloud.githubusercontent.com/assets/2712405/18008606/c1dd68e2-6b76-11e6-8590-79e1f50f6b93.png)

**Comment by adriatic** [comment]
Repeated the yesterday's `npm install` run (by deleting the `node_modules` folder first:

Note the message `[10:30:50] [info] skeleton-esnext-aspnetcore@1.0.0~postinstall: Failed to exec postinstall script`

![image](https://cloud.githubusercontent.com/assets/2712405/18009244/60145528-6b79-11e6-9e67-e5b0fb106a82.png)

The difference between 953 and 350 seconds should be attributed to my faster machine.

**The same `npm install` task executed directly (without Monterey) took 161 seconds.**

**Comment by adriatic** [comment]
Back to `Error: Cannot find module 'skeleton-esnext-aspnetcore\src\skeleton\node_modules\jspm\api.js'` reported at the start of this thread.

I deleted the `node_modules` folder (with Files Explorer) and run `npm install` (in Cmder console). Then started Monterey, selected the [skeleton-esnext-aspnetcore](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/skeleton-esnext-aspnetcore.html) project and clicked on `NPM` tile - all seem just fine

![image](https://cloud.githubusercontent.com/assets/2712405/18009867/087c4160-6b7c-11e6-9749-6818367f279b.png)

Click on `JSPM` tile in this situation results with:

![image](https://cloud.githubusercontent.com/assets/2712405/18009932/4ea7fd1e-6b7c-11e6-83b6-737c331e14f2.png)

Monterey lies - as the file `api.js` clearly exists:

![image](https://cloud.githubusercontent.com/assets/2712405/18010008/bf114628-6b7c-11e6-8aff-24b3fce1890f.png)

**Comment by JeroenVinke** [comment]
Can you confirm that you are on `monterey-pal-electron@0.1.41`? check monterey's `jspm_packages/github/monterey-framework/` folder

**Comment by adriatic** [comment]
![image](https://cloud.githubusercontent.com/assets/2712405/18012020/9731ef78-6b85-11e6-8f3b-12a7dc13e186.png)

**Comment by JeroenVinke** [comment]
strange, it works fine for me (have tried multiple times)

can you open the debugger, browse to this file:

![image](https://cloud.githubusercontent.com/assets/2189477/18012307/4847a2fc-6bb9-11e6-9eac-785d8c50b44d.png)

then put a breakpoint on https://github.com/monterey-framework/monterey-pal-electron/blob/master/dist/commonjs/jspm.js#L57. Then open the JSPM package manager screen (where you are getting that error), and run `path.join(path.dirname(packageJSONPath), 'node_modules', 'jspm');` ?

**Comment by adriatic** [comment]
It seems that you fixed this, raising the question: do you want me to look into this with the debugger?? Unlikely, I think

**Comment by JeroenVinke** [comment]
Oops, may have used the wrong issue in the commit

**Comment by adriatic** [comment]
OK, then I will first do `git pull` and then look at this problem

**Comment by adriatic** [comment]
Luckily - the problem is still here:

```
DEBUG [aurelia] Loading plugin aurelia-templating-binding.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-templating-binding.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-templating-resources.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-templating-resources.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-event-aggregator.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-event-aggregator.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-history-browser.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-history-browser.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-templating-router.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-templating-router.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-dialog.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-dialog.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-v-grid.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-v-grid.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-validation.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-validation.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin aurelia-validatejs.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin aurelia-validatejs.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin context-menu.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin context-menu.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin landing/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin landing/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin main/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin main/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin scaffolding/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin scaffolding/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/app-launcher/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/app-launcher/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/npm/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/npm/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/jspm/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/jspm/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/aurelia-cli/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/aurelia-cli/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/gulp/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/gulp/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/webpack/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/webpack/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/project-info/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/project-info/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/preferences/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/preferences/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/gist-run/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/gist-run/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/errors/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/errors/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/support/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/support/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/terminal/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/terminal/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/task-manager/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/task-manager/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Loading plugin plugins/about/index.
aurelia-logging-console.js:24 DEBUG [aurelia] Configured plugin plugins/about/index.
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/compose.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-router@1.0.0/router-view.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/ai-dialog.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/ai-dialog-header.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/ai-dialog-body.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-dialog@1.0.0-beta.3.0.0/ai-dialog-footer.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.1.0/vGrid/v-grid-element-row-repeat.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.1.0/vGrid/v-grid-element-col-config.js Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.1.0/vGrid/v-grid.html Array[7]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/monterey-framework/context-menu@1.0.0/menu.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/aurelia-ui-toolkits/aurelia-v-grid@0.1.0/vGrid/v-grid-element-footer-pager.html Array[0]
aurelia-logging-console.js:34 INFO [aurelia] Aurelia Started
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/app.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/main/main.html Array[3]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/main/components/project-list.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/main/components/tiles.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-bar/task-bar.html Array[0]
aurelia-logging-console.js:34 INFO [updater] current version: v0.2.4
aurelia-logging-console.js:34 INFO [updater] using update feed url: https://nuts.jeroenvinke.nl:443/update/win32/
aurelia-logging-console.js:34 INFO [updater] checking for updates now
aurelia-logging-console.js:34 INFO [updater] Error: Failed to update: Error: Can not find Squirrel
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/default-tile.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/preferences/task-bar.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/errors/task-bar.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/terminal/task-bar.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/support/task-bar.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/about/task-bar.html Array[1]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-bar/task-bar-item.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-manager/task-bar.html Array[1]
2aurelia-logging-console.js:34 INFO [application-state] State saved
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/npm/screen.html Array[0]
aurelia-logging-console.js:24 DEBUG [templating] importing resources for file:///C:/work/monterey-framework/monterey/app/dist/plugins/jspm/screen.html Array[0]
aurelia-logging-console.js:54 ERROR [notification] Error loading JSPM dependencies: Cannot find module 'skeleton-esnext-aspnetcore\src\skeleton\node_modules\jspm\api.js'error @ aurelia-logging-console.js:54
screen.ts:55Error: Cannot find module 'skeleton-esnext-aspnetcore\src\skeleton\node_modules\jspm\api.js'(…)
aurelia-logging-console.js:34 INFO [app-launcher] going to run cmd: "start explorer "skeleton-esnext-aspnetcore"", without shell
```

**Note these errors**

```
aurelia-logging-console.js:34 INFO [updater] current version: v0.2.4
aurelia-logging-console.js:34 INFO [updater] using update feed url: https://nuts.jeroenvinke.nl:443/update/win32/
aurelia-logging-console.js:34 INFO [updater] checking for updates now
aurelia-logging-console.js:34 INFO [updater] Error: Failed to update: Error: Can not find Squirrel
```

**Comment by adriatic** [comment]
Breakpoint set:

![image](https://cloud.githubusercontent.com/assets/2712405/18019202/0938559e-6ba9-11e6-9ea3-a0e9b6211201.png)

Step over:

![image](https://cloud.githubusercontent.com/assets/2712405/18019275/415cfb82-6ba9-11e6-8b9a-f094e81d36ba.png)

A few step-in, step-out commands resulted with:

![image](https://cloud.githubusercontent.com/assets/2712405/18019451/31a730d0-6baa-11e6-93b9-77619fde702d.png)

**Warning**

Keeping these breakpoints set I let the debugger go and found out that it fails a lot later than first time through that code. So, while everything I recorded above seem fine, the problems appear later.

**Comment by JeroenVinke** [comment]
Maybe we should try absolute paths instead of "skeleton-esnext\src\node_modules\jspm\jspm.js" will make this change tomorrow

**Comment by adriatic** [comment]
That is the approach that I **always** take, thinking that relative paths are "too risky".

However, making this change should not explain how does the same code work for you. So, I will (later) get a fresh clone of monterey to verify this situation

**Comment by JeroenVinke** [comment]
It should be a full path

[here](https://github.com/monterey-framework/monterey/blob/master/app/src/plugins/jspm/screen.ts#L44) we call the check for whether or not jspm is installed. The packagejsonpath of the project is passed, which (atleast in my case) is always a full path. If this is a relative path for you then it should also show up as a relative path in the project information screen

**Comment by adriatic** [comment]
> If this is a relative path for you then it should also show up as a relative path in the project information screen

I will check that - once I reinstall a fresh clone (keeping all projects of course)

**Comment by adriatic** [comment]
It seems that this issue is gone - as described in https://github.com/monterey-framework/monterey/issues/216

**Comment by JeroenVinke** [comment]
ok, lets continue in https://github.com/monterey-framework/monterey/issues/216
