### ISSUE TITLE
Received all these warnings ...

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#240]
while working in screen-shots for 

```
TypeError: Path must be a string. Received [ 'C:\\work\\tests\\Monterey-testing-08302016' ]
    at assertPath (path.js:7:11)
    at join (path.js:466:7)
    at Object.join (file:///C:/work/monterey-framework/monterey/app/jspm_packages/github/monterey-framework/monterey-pal-electron@0.1.43/fs.js:231:22)
    at ProjectName.<anonymous> (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:53:42)
    at next (<anonymous>)
    at file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:16:65
    at __awaiter (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:12:12)
    at ProjectName.checkFolderExistence (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:50:16)
    at ProjectName.attached (file:///C:/work/monterey-framework/monterey/app/dist/scaffolding/project-name.js:43:14)
    at Controller.attached (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js:3471:24)
```

Did not observe this while running this project, so this may suggest a less subtle warning

**Comment by JeroenVinke** [comment]
https://github.com/monterey-framework/monterey/commit/785b97a2fc311eaf7d522163e1f797cd0159c746
