### ISSUE TITLE
Task runner is misbehaving (Cannot read property 'animatableElement' of undefined)

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#263]
![image](https://cloud.githubusercontent.com/assets/2189477/18210408/99dc33b0-7138-11e6-8173-d134254ad941.png)

Issue: when the task runner is still busy  fetching all tasks for a project (indicated by a spinner), the user is still allowed to switch projects. This project then also starts to load tasks and show a spinner, causing some weird things to happen

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18210470/f0cf0846-7138-11e6-947b-50ba77f9ee92.png)

```
TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js:1601:13)
    at ViewSlot.animateView (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js:1640:31)
    at ViewSlot.removeAt (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.0/aurelia-templating.js:1842:30)
    at Repeat.removeView (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:284:28)
    at ArrayRepeatStrategy._runSplices (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:199:38)
    at ArrayRepeatStrategy.instanceMutated (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:166:31)
    at Repeat.handleCollectionMutated (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:172:21)
    at Repeat.call (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:116:20)
    at ModifyArrayObserver.callSubscribers (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.1/aurelia-binding.js:366:19)
    at ModifyArrayObserver.call (file:///C:/Development/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.1/aurelia-binding.js:980:14)
```

**Comment by adriatic** [comment]
This is **sufficiently important** to make our planned delivery depend on this fixed and retested. I am glad you caught it as I was so focused in making good screenshots that did not dare to try something "semi-mischievous"
