### ISSUE TITLE
 spawn au ENOENT

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#271]
While trying to start the `au run --watch` task on mac:
```
Error: spawn au ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by JeroenVinke** [comment]
Ah yes, I did not install aurelia-cli globally. Something we should document and add a warning for

**Comment by JeroenVinke** [comment]
now that i'm thinking of this, https://github.com/dotnet/cli#installers-and-binaries is needed for `dotnet` commands

**Comment by adriatic** [comment]
Of course - and once having these binaries installed, we will help Microsoft to penetrate Mac development more than any of their CLI stuff (yep, sounding cocky - but some good marketing will do it)
