### ISSUE TITLE
dotnet command fails on mac

### ISSUE THREAD

**Issue by JeroenVinke** [monterey-framework/monterey#274]
monterey runs `dotnet --help` to check whether or not dotnet is installed, but this fails even though `dotnet --help` from the terminal works fine
```
Error: Command failed: dotnet --help

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

monterey is nice about it though, and did not add dotnet commands to the workflow
![image](https://cloud.githubusercontent.com/assets/2189477/18218924/20fcf762-7166-11e6-8d0d-aab228af450c.png)

**Comment by JeroenVinke** [comment]
This means that dotnet samples do not work automagically on mac (yet)

**Comment by JeroenVinke** [comment]
1. I did not install .net core SDK (just .net core)
2. after installing .net core sdk I needed to install openSSL (also shown [here](https://www.microsoft.com/net/core#macos)) because otherwise you get 

  <details>
  ```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
   ```
  </details>

3. Then after `dotnet restore`:

  <details>
  ```
Jeroens-Mac:skeleton jeroen$ dotnet restore
log  : Restoring packages for /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
error: Too many open files
log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.threading.threadpool/4.0.10/system.threading.threadpool.4.0.10.nupkg'.
log  : Too many open files

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   at System.Diagnostics.StackTraceSymbols..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
   at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 iSkip, Boolean fNeedFileInfo, Thread targetThread, Exception e)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.AggregateException.ToString()
   at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)

  ```
  </details>

4. After running `ulimit -n 2048` (https://github.com/dotnet/coreclr/issues/2054#issuecomment-157586745) it got a bit further:

  <details>
  ```
Jeroens-Mac:skeleton jeroen$ dotnet restore
log  : Restoring packages for /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Installing Microsoft.Composition 1.0.27.
log  : Installing Microsoft.CodeAnalysis.Workspaces.Common 1.3.0.
log  : Installing Microsoft.CodeAnalysis.CSharp.Workspaces 1.3.0.
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Utils 1.0.0-preview2-final.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing System.Runtime.Handles 4.0.0.
log  : Installing System.Xml.XPath 4.0.1.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Templating 1.0.0-preview2-final.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.0.
log  : Installing System.Runtime.InteropServices 4.0.20.
log  : Installing System.IO.FileSystem 4.0.0.
error: Access to the path '/Users/jeroen/.nuget/packages/microsoft.composition/1.0.27' is denied.
error:   Permission denied
  ```
  </details>
4. after nuking the .nuget folder (it was probably created by root once):
  <details>
  ```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3026 ms
Expanding 100% 6022 ms
log  : Restoring packages for /private/var/folders/_1/x2mdntnd50sdhs1384qdxvhh0000gn/T/ah0lpxvx.r0o/project.json...
log  : Installing System.Xml.XPath 4.0.1.
log  : Installing runtime.native.System.IO.Compression 4.1.0.
log  : Installing Microsoft.NETCore.DotNetHost 1.0.1.
log  : Installing Microsoft.NETCore.Targets 1.0.1.
log  : Installing System.Xml.XPath.XDocument 4.0.1.
log  : Installing System.Xml.XmlDocument 4.0.1.
log  : Installing System.Text.Encoding.CodePages 4.0.1.
log  : Installing System.Diagnostics.StackTrace 4.0.1.
log  : Installing System.Diagnostics.FileVersionInfo 4.0.0.
log  : Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
log  : Installing System.Security.Cryptography.Csp 4.0.0.
log  : Installing System.Security.Cryptography.Cng 4.2.0.
log  : Installing runtime.native.System.Net.Http 4.0.1.
log  : Installing System.Security.Principal 4.0.1.
log  : Installing System.Security.Cryptography.OpenSsl 4.0.0.
log  : Installing System.Security.Claims 4.0.1.
log  : Installing Microsoft.NETCore.App 1.0.0.
log  : Installing Libuv 1.9.0.
log  : Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
log  : Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
log  : Installing runtime.native.System.Security.Cryptography 4.0.0.
log  : Installing runtime.native.System.Net.Security 4.0.1.
log  : Installing System.Security.Principal.Windows 4.0.0.
log  : Installing Microsoft.CSharp 4.0.1.
log  : Installing System.Reflection.Emit.Lightweight 4.0.1.
log  : Installing System.Threading.Overlapped 4.0.1.
log  : Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
log  : Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2.
log  : Installing Microsoft.VisualBasic 10.0.1.
log  : Installing NETStandard.Library 1.6.0.
log  : Installing System.Buffers 4.0.0.
log  : Installing System.Reflection.Emit.ILGeneration 4.0.1.
log  : Installing System.Collections.Immutable 1.2.0.
log  : Installing System.Reflection.Emit 4.0.1.
log  : Installing System.ComponentModel 4.0.1.
log  : Installing System.ComponentModel.Annotations 4.1.0.
log  : Installing runtime.native.System 4.0.0.
log  : Installing Microsoft.Win32.Registry 4.0.0.
log  : Installing System.Diagnostics.DiagnosticSource 4.0.0.
log  : Installing System.Diagnostics.Process 4.1.0.
log  : Installing System.Xml.XDocument 4.0.11.
log  : Installing System.Dynamic.Runtime 4.0.11.
log  : Installing System.Globalization.Extensions 4.0.1.
log  : Installing System.IO.FileSystem.Watcher 4.0.0.
log  : Installing System.IO.MemoryMappedFiles 4.0.0.
log  : Installing System.IO.UnmanagedMemoryStream 4.0.1.
log  : Installing System.Linq.Expressions 4.1.0.
log  : Installing System.Xml.ReaderWriter 4.0.11.
log  : Installing System.Linq.Parallel 4.0.1.
log  : Installing System.Linq.Queryable 4.0.1.
log  : Installing System.Net.NameResolution 4.0.0.
log  : Installing System.Net.Requests 4.0.11.
log  : Installing System.Net.Security 4.0.0.
log  : Installing System.Net.WebHeaderCollection 4.0.1.
log  : Installing System.Numerics.Vectors 4.1.1.
log  : Installing System.Reflection.DispatchProxy 4.0.1.
log  : Installing System.Reflection.Metadata 1.3.0.
log  : Installing System.Threading.Timer 4.0.1.
log  : Installing System.Reflection.TypeExtensions 4.1.0.
log  : Installing System.Resources.Reader 4.0.0.
log  : Installing System.Runtime.Loader 4.0.0.
log  : Installing System.Security.Cryptography.Algorithms 4.2.0.
log  : Installing System.Security.Cryptography.Encoding 4.0.0.
log  : Installing System.Security.Cryptography.Primitives 4.0.0.
log  : Installing System.Security.Cryptography.X509Certificates 4.1.0.
log  : Installing System.Threading.Tasks.Dataflow 4.6.0.
log  : Installing System.Threading.Tasks.Extensions 4.0.0.
log  : Installing System.Threading.Tasks.Parallel 4.0.1.
log  : Installing System.Threading.Thread 4.0.0.
log  : Installing System.Threading.ThreadPool 4.0.10.
log  : Installing Microsoft.NETCore.Platforms 1.0.1.
log  : Installing Microsoft.CodeAnalysis.Common 1.3.0.
log  : Installing System.Collections 4.0.11.
log  : Installing System.Diagnostics.Debug 4.0.11.
log  : Installing System.Globalization 4.0.11.
log  : Installing System.Linq 4.1.0.
log  : Installing System.ObjectModel 4.0.12.
log  : Installing System.Reflection 4.1.0.
log  : Installing System.Reflection.Extensions 4.0.1.
log  : Installing System.Reflection.Primitives 4.0.1.
log  : Installing System.Resources.ResourceManager 4.0.1.
log  : Installing System.Runtime 4.1.0.
log  : Installing System.Runtime.Extensions 4.1.0.
log  : Installing System.Runtime.InteropServices 4.1.0.
log  : Installing System.Threading 4.0.11.
log  : Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
log  : Installing Microsoft.NETCore.Jit 1.0.2.
log  : Installing Microsoft.NETCore.Windows.ApiSets 1.0.1.
log  : Installing Microsoft.Win32.Primitives 4.0.1.
log  : Installing System.AppContext 4.1.0.
log  : Installing System.Collections.Concurrent 4.0.12.
log  : Installing System.Console 4.0.0.
log  : Installing System.Diagnostics.Tools 4.0.1.
log  : Installing System.Diagnostics.Tracing 4.1.0.
log  : Installing System.Globalization.Calendars 4.0.1.
log  : Installing System.IO 4.1.0.
log  : Installing System.IO.Compression 4.1.0.
log  : Installing System.IO.Compression.ZipFile 4.0.1.
log  : Installing System.IO.FileSystem 4.0.1.
log  : Installing System.IO.FileSystem.Primitives 4.0.1.
log  : Installing System.Net.Http 4.1.0.
log  : Installing System.Net.Primitives 4.0.11.
log  : Installing System.Net.Sockets 4.1.0.
log  : Installing System.Runtime.Handles 4.0.1.
log  : Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
log  : Installing System.Runtime.Numerics 4.0.1.
log  : Installing System.Text.Encoding 4.0.11.
log  : Installing System.Text.Encoding.Extensions 4.0.11.
log  : Installing System.Text.RegularExpressions 4.1.0.
log  : Installing System.Threading.Tasks 4.0.11.
log  : Writing lock file to disk. Path: /private/var/folders/_1/x2mdntnd50sdhs1384qdxvhh0000gn/T/ah0lpxvx.r0o/project.lock.json
log  : /private/var/folders/_1/x2mdntnd50sdhs1384qdxvhh0000gn/T/ah0lpxvx.r0o/project.json
log  : Restore completed in 3067ms.
log  : Restoring packages for /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Installing Microsoft.Composition 1.0.27.
log  : Installing Microsoft.CodeAnalysis.Workspaces.Common 1.3.0.
log  : Installing Microsoft.CodeAnalysis.CSharp.Workspaces 1.3.0.
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Utils 1.0.0-preview2-final.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing System.Runtime.Handles 4.0.0.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Templating 1.0.0-preview2-final.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.0.
log  : Installing System.IO.FileSystem.Primitives 4.0.0.
log  : Installing System.IO.FileSystem 4.0.0.
log  : Installing System.Runtime.InteropServices 4.0.20.
log  : Installing Microsoft.ApplicationInsights.AspNetCore 1.0.0.
log  : Installing Microsoft.AspNetCore.Authentication.Cookies 1.0.0.
log  : Installing Microsoft.AspNetCore.Diagnostics 1.0.0.
log  : Installing Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 1.0.0.
log  : Installing Microsoft.AspNetCore.Identity.EntityFrameworkCore 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc 1.0.0.
log  : Installing Microsoft.AspNetCore.Razor.Tools 1.0.0-preview2-final.
log  : Installing Microsoft.AspNetCore.Server.IISIntegration 1.0.0.
log  : Installing Microsoft.AspNetCore.Server.Kestrel 1.0.0.
log  : Installing Microsoft.AspNetCore.StaticFiles 1.0.0.
log  : Installing Microsoft.EntityFrameworkCore.SqlServer 1.0.0.
log  : Installing Microsoft.EntityFrameworkCore.Tools 1.0.0-preview2-final.
log  : Installing Microsoft.Extensions.Configuration.EnvironmentVariables 1.0.0.
log  : Installing Microsoft.Extensions.Configuration.Json 1.0.0.
log  : Installing Microsoft.Extensions.Configuration.UserSecrets 1.0.0.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Core 1.0.0-preview2-final.
log  : Installing Microsoft.Extensions.Logging.Console 1.0.0.
log  : Installing Microsoft.Extensions.Logging 1.0.0.
log  : Installing Microsoft.EntityFrameworkCore.Relational.Design 1.0.0.
log  : Installing Microsoft.Extensions.Logging.Debug 1.0.0.
log  : Installing Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0.
log  : Installing Microsoft.VisualStudio.Web.CodeGenerators.Mvc 1.0.0-preview2-final.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.Tools 1.0.0-preview2-final.
log  : Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
log  : Installing Microsoft.ApplicationInsights 2.1.0.
log  : Installing Newtonsoft.Json 6.0.4.
log  : Installing Microsoft.AspNetCore.Hosting.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Http.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.ViewFeatures 1.0.0.
log  : Installing Microsoft.Extensions.Configuration 1.0.0.
log  : Installing Microsoft.Extensions.DiagnosticAdapter 1.0.0.
log  : Installing Microsoft.Extensions.Logging.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Authentication 1.0.0.
log  : Installing Microsoft.Extensions.Options 1.0.0.
log  : Installing Microsoft.Extensions.WebEncoders 1.0.0.
log  : Installing Microsoft.AspNetCore.Diagnostics.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Http.Extensions 1.0.0.
log  : Installing Microsoft.Extensions.FileProviders.Physical 1.0.0.
log  : Installing Microsoft.AspNetCore.WebUtilities 1.0.0.
log  : Installing Microsoft.EntityFrameworkCore.Relational 1.0.0.
log  : Installing System.ComponentModel.TypeConverter 4.1.0.
log  : Installing Microsoft.AspNetCore.Identity 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.ApiExplorer 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Cors 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.DataAnnotations 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Formatters.Json 1.0.0.
log  : Installing runtime.win7-x86.runtime.native.System.Data.SqlClient.sni 4.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.Localization 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Razor 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.TagHelpers 1.0.0.
log  : Installing runtime.win7-x64.runtime.native.System.Data.SqlClient.sni 4.0.1.
log  : Installing Microsoft.Extensions.Caching.Memory 1.0.0.
log  : Installing NuGet.DependencyResolver.Core 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.DependencyInjection 1.0.0.
log  : Installing Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121.
log  : Installing System.Runtime.Serialization.Primitives 4.1.1.
log  : Installing NuGet.Packaging.Core 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.Razor.Runtime 1.0.0.
log  : Installing Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121.
log  : Installing Microsoft.Extensions.CommandLineUtils 1.0.0.
log  : Installing Microsoft.Extensions.PlatformAbstractions 1.0.0.
log  : Installing Newtonsoft.Json 9.0.1.
log  : Installing Microsoft.AspNetCore.Http 1.0.0.
log  : Installing NuGet.Common 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.Globalization.CultureInfoCache 1.0.0.
log  : Installing Microsoft.AspNetCore.HttpOverrides 1.0.0.
log  : Installing Microsoft.Extensions.Localization.Abstractions 1.0.0.
log  : Installing System.Interactive.Async 3.0.0.
log  : Installing Microsoft.Extensions.FileProviders.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Hosting 1.0.0.
log  : Installing System.Data.SqlClient 4.1.0.
log  : Installing Remotion.Linq 2.1.1.
log  : Installing Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121.
log  : Installing Microsoft.EntityFrameworkCore.Design 1.0.0-preview2-final.
log  : Installing Microsoft.Extensions.Configuration.FileExtensions 1.0.0.
log  : Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0.
log  : Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration 1.0.0-preview2-final.
log  : Installing System.Diagnostics.Contracts 4.0.1.
log  : Installing System.Collections 4.0.10.
log  : Installing System.Diagnostics.Debug 4.0.10.
log  : Installing System.Diagnostics.Tools 4.0.0.
log  : Installing System.Diagnostics.Tracing 4.0.20.
log  : Installing Microsoft.AspNetCore.DataProtection.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Cryptography.Internal 1.0.0.
log  : Installing Microsoft.AspNetCore.Routing 1.0.0.
log  : Installing System.IO 4.0.10.
log  : Installing System.Globalization 4.0.10.
log  : Installing Microsoft.AspNetCore.Mvc.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Authorization 1.0.0.
log  : Installing System.Net.WebSockets 4.0.0.
log  : Installing System.IO.Compression 4.0.0.
log  : Installing System.Linq 4.0.0.
log  : Installing System.Net.Http 4.0.0.
log  : Installing System.Xml.ReaderWriter 4.0.10.
log  : Installing System.Reflection 4.0.10.
log  : Installing System.Reflection.Extensions 4.0.0.
log  : Installing System.Runtime 4.0.20.
log  : Installing System.Private.Uri 4.0.0.
log  : Installing System.Reflection.Primitives 4.0.0.
log  : Installing System.Runtime.Extensions 4.0.10.
log  : Installing System.Text.Encoding 4.0.10.
log  : Installing System.Net.Primitives 4.0.0.
log  : Installing System.Text.Encoding.Extensions 4.0.10.
log  : Installing System.Text.RegularExpressions 4.0.10.
log  : Installing System.Threading 4.0.10.
log  : Installing System.Runtime.InteropServices 4.0.0.
log  : Installing System.Threading.Tasks 4.0.10.
log  : Installing System.Xml.XDocument 4.0.10.
log  : Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Http.Features 1.0.0.
log  : Installing System.Text.Encodings.Web 4.0.0.
log  : Installing Microsoft.AspNetCore.Antiforgery 1.0.0.
log  : Installing Microsoft.AspNetCore.Html.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Core 1.0.0.
log  : Installing Microsoft.AspNetCore.DataProtection 1.0.0.
log  : Installing Microsoft.Extensions.Primitives 1.0.0.
log  : Installing System.Resources.ResourceManager 4.0.0.
log  : Installing Microsoft.Net.Http.Headers 1.0.0.
log  : Installing Microsoft.Extensions.FileSystemGlobbing 1.0.0.
log  : Installing System.Data.Common 4.1.0.
log  : Installing Microsoft.EntityFrameworkCore 1.0.0.
log  : Installing System.Collections.NonGeneric 4.0.1.
log  : Installing Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 1.0.0-preview2-final.
log  : Installing Microsoft.EntityFrameworkCore.Design.Core 1.0.0-preview2-final.
log  : Installing NuGet.RuntimeModel 3.5.0-beta2-1484.
log  : Installing System.Collections.Specialized 4.0.1.
log  : Installing Microsoft.Extensions.DependencyModel 1.0.0.
log  : Installing System.IO.Pipes 4.0.0.
log  : Installing System.ComponentModel.Primitives 4.1.0.
log  : Installing Microsoft.AspNetCore.Cryptography.KeyDerivation 1.0.0.
log  : Installing Microsoft.AspNetCore.Cors 1.0.0.
log  : Installing Microsoft.Extensions.Localization 1.0.0.
log  : Installing Microsoft.AspNetCore.JsonPatch 1.0.0.
log  : Installing runtime.native.System.Data.SqlClient.sni 4.0.0.
log  : Installing Microsoft.AspNetCore.Localization 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Razor.Host 1.0.0.
log  : Installing Microsoft.Extensions.FileProviders.Composite 1.0.0.
log  : Installing Microsoft.Extensions.ObjectPool 1.0.0.
log  : Installing Microsoft.Extensions.Caching.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Razor 1.0.0.
log  : Installing NuGet.Versioning 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging 3.5.0-beta2-1484.
log  : Installing NuGet.ProjectModel 3.5.0-beta2-1484.
log  : Installing NuGet.Frameworks 3.5.0-beta2-1484.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Installing Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-preview2-final.
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Restoring packages for tool 'Microsoft.Extensions.SecretManager.Tools' in /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Installing Microsoft.Extensions.SecretManager.Tools 1.0.0-preview2-final.
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json...
log  : Writing lock file to disk. Path: /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.lock.json
log  : /Users/jeroen/Development/scaffolded/skeleton-typescript-aspnetcore2/src/skeleton/project.json
log  : Restore completed in 7873ms
  ```

**Comment by JeroenVinke** [comment]
![image](https://cloud.githubusercontent.com/assets/2189477/18223647/1c228aba-71be-11e6-9c5e-5ad0a3a6fa31.png)
