### ISSUE TITLE
Error running aurelia-cli custom generator created app

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#296]
Project info:

* **Project name**
cli-custom-1
* **Project path:**
C:\work\tests\Monterey-testing-09092016\cli-custom-1
* **NodeJS:**
6.3.0
* **NPM:**
3.10.6
* **Electron:**
1.3.5
* **Chrome:**
52.0.2743.82
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-09092016\cli-custom-1\package.json
* **Project is using Aurelia-CLI**
* **aurelia.json path:**
C:\work\tests\Monterey-testing-09092016\cli-custom-1\aurelia_project\aurelia.json

**Running it I get**
```
TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1601:13)
    at ViewSlot.animateView (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1640:31)
    at ViewSlot.removeAt (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating@1.0.1/aurelia-templating.js:1842:30)
    at Repeat.removeView (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:284:28)
    at ArrayRepeatStrategy._runSplices (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:199:38)
    at ArrayRepeatStrategy.instanceMutated (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/array-repeat-strategy.js:166:31)
    at Repeat.handleCollectionMutated (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:172:21)
    at Repeat.call (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-templating-resources@1.0.0/repeat.js:116:20)
    at ModifyArrayObserver.callSubscribers (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.3/aurelia-binding.js:366:19)
    at ModifyArrayObserver.call (file:///C:/work/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.3/aurelia-binding.js:980:14)
```

**Comment by adriatic** [comment]
This is a good case to tell me what all should be supplied to Monterey support in this situation.

**Comment by JeroenVinke** [comment]
This error is equivalent to https://github.com/monterey-framework/monterey/issues/270 and should not stop the application from running. I will refactor the code behind the task runner part of the TaskManager to resolve this issue. Current implementation leaves much room for improvement :)

**Comment by adriatic** [comment]
Yes, I had the feeling that `animatableElement` sounded familiar.
