### ISSUE TITLE
Disallow adding empty task to favorites

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#322]
### Intention

**I'm submitting a bug report**  

![image](https://cloud.githubusercontent.com/assets/2712405/18617080/49911fb4-7d96-11e6-8f05-07351f72b24f.png)

Note: it can also be removed 😏

**Comment by adriatic** [comment]
Also: please create a md file (in this issue, I guess) describing what should be happening here. Should it not be better to offer a fixed selection of things to add, instead of typing a string and defining the **`command`** by that?

**Comment by adriatic** [comment]
Addeed later

I just realized that Monterey correctly reports the above problem:

```
Error: task execute function and title are required
    at TaskManager.addTask (file:///C:/work/monterey-framework/monterey/app/dist/plugins/task-manager/task-manager.js:31:19)
    at tasks.forEach.task (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/workflow.js:36:30)
    at Array.forEach (native)
    at Workflow.start (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/workflow.js:32:15)
    at Tile.start (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/tile.js:80:23)
    at Tile.<anonymous> (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/tile.js:63:22)
    at next (<anonymous>)
    at file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/tile.js:16:65
    at __awaiter (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/tile.js:12:12)
    at Tile.onClick (file:///C:/work/monterey-framework/monterey/app/dist/plugins/workflow/tile.js:52:16)
```

I suggest to show the error notice with `Error: task execute function and title are required` instead of the

![image](https://cloud.githubusercontent.com/assets/2712405/18617184/c65ac6fc-7d97-11e6-8e47-ac65d32bc2dd.png)
