### ISSUE TITLE
skeleton-esnext-webpack fails on Windows

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#338]
### Intention

**I'm submitting a bug report**  

### Environment

* **Project name**
skeleton-esnext-webpack
* **Project path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack
* **NodeJS:**
6.5.0
* **NPM:**
3.10.8
* **Electron:**
1.4.0
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\package.json
* **Project is using Webpack**
* **Webpack.config.js path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\webpack.config.js

### Description
**Current behavior:**  

![image](https://cloud.githubusercontent.com/assets/2712405/18770917/3fcc78aa-8108-11e6-95ec-a287abbd99ed.png)

Console content:

```
[21:01:30] -----STARTED-----
[21:01:35] > skeleton-esnext-webpack@1.0.0 start C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack
[21:01:35] > npm run server:dev
[21:01:36] > skeleton-esnext-webpack@1.0.0 server:dev C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack
[21:01:36] > cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch
[21:01:42] C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\node_modules\webpack\lib\webpack.js:16
[21:01:42] throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
[21:01:42] ^
[21:01:42] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
[21:01:42] - configuration has an unknown property 'debug'. These properties are valid:
[21:01:42] object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
[21:01:42] The 'debug' property was removed in webpack 2.
[21:01:42] Loaders should be updated to allow passing this option via loader options in module.rules.
[21:01:42] Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
[21:01:42] plugins: {
[21:01:42] new webpack.LoaderOptionsPlugin({
[21:01:42] debug: true
[21:01:42] })
[21:01:42] }
[21:01:42] - configuration.resolve has an unknown property 'root'. These properties are valid:
[21:01:42] object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
[21:01:42] at webpack (C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\node_modules\webpack\lib\webpack.js:16:9)
[21:01:42] at processOptions (C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\node_modules\webpack-dev-server\bin\webpack-dev-server.js:269:17)
[21:01:42] at Object.<anonymous> (C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\node_modules\webpack-dev-server\bin\webpack-dev-server.js:297:1)
[21:01:42] at Module._compile (module.js:541:32)
[21:01:42] at Object.Module._extensions..js (module.js:550:10)
[21:01:42] at Module.load (module.js:458:32)
[21:01:42] at tryModuleLoad (module.js:417:12)
[21:01:42] at Function.Module._load (module.js:409:3)
[21:01:42] at Module.runMain (module.js:575:10)
[21:01:42] at run (bootstrap_node.js:352:7)
[21:01:42] at startup (bootstrap_node.js:144:9)
[21:01:42] at bootstrap_node.js:467:3
[21:01:42] npm ERR! Windows_NT 10.0.10586
[21:01:42] npm ERR!
[21:01:42] argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev"
[21:01:42] npm ERR! node v6.3.1
[21:01:42] npm ERR! npm v3.10.7
[21:01:42] npm ERR! code ELIFECYCLE
[21:01:42] npm ERR! skeleton-esnext-webpack@1.0.0 server:dev: `cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch`
[21:01:42] npm ERR! Exit status 1
[21:01:42] npm ERR!
[21:01:42] npm ERR! Failed at the skeleton-esnext-webpack@1.0.0 server:dev script 'cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch'.
[21:01:42] npm ERR! Make sure you have the latest version of node.js and npm installed.
[21:01:42] npm ERR! If you do, this is most likely a problem with the skeleton-esnext-webpack package,
[21:01:42] npm ERR! not with npm itself.
[21:01:42] npm ERR! Tell the author that this fails on your system:
[21:01:42] npm ERR! cross-env NODE_ENV=development node ./node_modules/webpack-dev-server/bin/webpack-dev-server --inline --progress --profile --watch
[21:01:42] npm ERR! You can get information on how to open an issue for this project with:
[21:01:42] npm ERR! npm bugs skeleton-esnext-webpack
[21:01:42] npm ERR! Or if that isn't available, you can get their info via:
[21:01:42] npm ERR! npm owner ls skeleton-esnext-webpack
[21:01:42] npm ERR! There is likely additional logging output above.
[21:01:42] npm ERR! Please include the following file with any support request:
[21:01:42] npm ERR! C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\npm-debug.log
[21:01:42] npm ERR! Windows_NT 10.0.10586
[21:01:42] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
[21:01:42] npm ERR! node v6.3.1
[21:01:42] npm ERR! npm v3.10.7
[21:01:42] npm ERR! code ELIFECYCLE
[21:01:42] npm ERR! skeleton-esnext-webpack@1.0.0 start: `npm run server:dev`
[21:01:42] npm ERR! Exit status 1
[21:01:42] npm
[21:01:42] ERR!
[21:01:42] npm ERR! Failed at the skeleton-esnext-webpack@1.0.0 start script 'npm run server:dev'.
[21:01:42] npm ERR! Make sure you have the latest version of node.js and npm installed.
[21:01:42] npm ERR! If you do, this is most likely a problem with the skeleton-esnext-webpack package,
[21:01:42] npm ERR! not with npm itself.
[21:01:42] npm ERR! Tell the author that this fails on your system:
[21:01:42] npm ERR! npm run server:dev
[21:01:42] npm ERR! You can get information on how to open an issue for this project with:
[21:01:42] npm ERR! npm bugs skeleton-esnext-webpack
[21:01:42] npm ERR! Or if that isn't available, you can get their info via:
[21:01:42] npm ERR! npm owner ls skeleton-esnext-webpack
[21:01:42] npm ERR! There is likely additional logging output above.
[21:01:42] npm ERR! Please include the following file with any support request:
[21:01:42] npm ERR! C:\work\tests\Monterey-testing-09222016\skeleton-esnext-webpack\npm-debug.log
[21:01:42] -----FINISHED-----
```
**Expected/desired behavior:**  

**What is the motivation / use case for changing the behavior?**  

### Logs

[2016-09-22.txt](https://github.com/monterey-framework/monterey/files/488696/2016-09-22.txt)

**Comment by adriatic** [comment]
### Note: it would be good  to rename the log file - from `file.csv` to `file.txt`

**Comment by adriatic** [comment]
I just verified that `skeleton-typescript-webpack` fails the same way.

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/skeleton-navigation/issues/670#issuecomment-248271154

**Comment by adriatic** [comment]
What do we do with Monterey release? Assuming that the project template for webpack based app creation reference to the "most current release (zip file), we should simply create the blog article called `release notes` and explain why not to use these templates until we announce that problems were fixed

**Comment by JeroenVinke** [comment]
Yeah is the question of "it is someone elses problem, but it is also our problem". I do not think we are the right group of people to fix a webpack issue, and we cant make changes to the repository

**Comment by adriatic** [comment]
So, I am taking your response as yes, we should go ahead with the release?

**Comment by JeroenVinke** [comment]
https://github.com/aurelia/skeleton-navigation/issues/670#issuecomment-250144786

We should confirm that this is fixed
