### ISSUE TITLE
The 'skeleton-esnext' project fails to run 

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#345]
### Intention

 
**I'm submitting a bug report**  

### Environment
* **Project name**
skeleton-esnext
* **Project path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext
* **NodeJS:**
6.5.0
* **NPM:**
3.10.8
* **Electron:**
1.4.1
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32
* **Project is using NPM**
* **Package.json path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext\package.json
* **Project is using JSPM**
* **JSPM version:**
0.16.41
* **Config.js path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext\config.js
* **Project is using Gulp**
* **gulpfile.js path:**
C:\work\tests\Monterey-testing-09222016\skeleton-esnext\gulpfile.js

### Description
**Current behavior:**  

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\renderer\api\remote.js:217:13)
    at remoteMemberFunction (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\renderer\api\remote.js:111:18)
    at EventEmitter.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\app.asar\jspm_packages\github\monterey-framework\monterey-pal-electron@0.1.47\jspm_commands.js:19:30)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at Object.exports.log (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\ui.js:89:24)
    at logInstall (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\install.js:514:8)
    at C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\install.js:327:9
    at tryCatch (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:521:7)
    at MutationObserver.flush (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:2370:5)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

as well as

```
TypeError: Cannot read property 'stack' of undefined
    at e.text (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/dist/plugins/errors/error-modal.js:41:42)
    at e.t [as onClick] (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9504)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9276)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:1175)
```

**Comment by adriatic** [comment]
Added few minutes later:

I cleared all errors, stopped `gulp watch` task, closed the task manager and clicked on the `Run` tile again

`Gulp watch` task finished seemingly corectly (here is the console content)

```
[00:10:37] -----STARTED-----
[00:10:52] Using gulpfile C:\work\tests\Monterey-testing-09222016\skeleton-esnext\gulpfile.js
[00:10:52] Starting 'build'...
[00:10:52] Starting 'unbundle'...
[00:10:52] Finished 'unbundle' after 49 ms
[00:10:52] Starting 'clean'...
[00:10:52] Finished 'clean' after 29 ms
[00:10:52] Starting 'build-system'...
[00:10:52] Starting 'build-html'...
[00:10:52] Starting 'build-css'...
[00:10:52] Finished 'build-css' after 5.69 ms
[00:10:54] Finished 'build-html' after 1.46 s
[00:10:54] Finished 'build-system' after 1.51 s
[00:10:54] Finished 'build' after 1.59 s
[00:10:54] Starting 'serve'...
[BS] Access URLs:
[00:10:56] ----------------------------
[00:10:56] Local: http://localhost:9000
[00:10:56] ----------------------------
[00:10:56] UI: http://localhost:3001
[00:10:56] ----------------------------
[BS] Serving files from: .
[00:10:56] Finished 'serve' after 2.25 s
[00:10:56] Starting 'watch'...
[00:10:56] Finished 'watch' after 16 ms
```

However the app failed to statrt with the following stack trace:

```
http://localhost:9000/jspm_packages/system.js Failed to load resource: the server responded with a status of 404 (Not Found)
config.js:1 Uncaught ReferenceError: System is not defined
localhost/:30 Uncaught ReferenceError: System is not defined
```

Are we possibly fetching this core from the Skeleton's master and someone screwed the source code??

**Comment by JeroenVinke** [comment]
I am missing the log file

**Comment by adriatic** [comment]
running `jspm install` in Cmder console

```
C:\work\skeletons\skeleton-navigation-1.0.0\skeleton-esnext  (aurelia-skeleton-navigation@1.0.0)                 
λ jspm install                                                                                                   
     Looking up npm:aurelia-animator-css                                                                         
     Looking up npm:aurelia-bootstrapper                                                                         
     Looking up npm:aurelia-fetch-client                                                                         
     Looking up npm:aurelia-framework                                                                            
     Looking up npm:aurelia-history-browser                                                                      
     Looking up npm:aurelia-loader-default                                                                       
     Looking up npm:aurelia-logging-console                                                                      
     Looking up npm:aurelia-pal-browser                                                                          
     Looking up npm:aurelia-polyfills                                                                            
     Looking up npm:aurelia-router                                                                               
     Looking up npm:aurelia-templating-binding                                                                   
     Looking up npm:aurelia-templating-resources                                                                 
     Looking up npm:aurelia-templating-router                                                                    
     Looking up npm:bluebird                                                                                     
     Looking up npm:font-awesome                                                                                 
     Looking up npm:jquery                                                                                       
     Looking up github:systemjs/plugin-text                                                                      
     Looking up github:twbs/bootstrap                                                                            
     Looking up github:github/fetch                                                                              
     Updating registry cache...                                                                                  
     Looking up npm:aurelia-event-aggregator                                                                     
     Looking up npm:aurelia-history                                                                              
     Looking up npm:aurelia-pal                                                                                  
     Looking up npm:aurelia-templating                                                                           
     Looking up npm:aurelia-metadata                                                                             
     Looking up npm:aurelia-binding                                                                              
     Looking up npm:aurelia-dependency-injection                                                                 
     Looking up npm:aurelia-loader                                                                               
     Looking up npm:aurelia-logging                                                                              
     Looking up npm:aurelia-path                                                                                 
     Looking up npm:aurelia-task-queue                                                                           
     Looking up npm:aurelia-route-recognizer                                                                     
     Looking up github:jspm/nodelibs-process                                                                     
     Looking up github:systemjs/plugin-css                                                                       
ok   Installed npm:aurelia-polyfills@^1.0.0 (1.0.0)                                                              
ok   Installed npm:aurelia-router@^1.0.1 (1.0.2)                                                                 
ok   Installed npm:aurelia-templating-router@^1.0.0 (1.0.0)                                                      
ok   Installed aurelia-fetch-client as npm:aurelia-fetch-client@^1.0.0-rc.1.0.0 (1.0.0)                          
ok   Installed npm:aurelia-logging-console@^1.0.0 (1.0.0)                                                        
ok   Installed npm:aurelia-framework@^1.0.0 (1.0.0)                                                              
ok   Installed npm:aurelia-history-browser@^1.0.0 (1.0.0)                                                        
ok   Installed npm:aurelia-loader-default@^1.0.0 (1.0.0)                                                         
ok   Installed text as github:systemjs/plugin-text@^0.0.8 (0.0.8)                                                
ok   Installed npm:aurelia-templating-resources@^1.0.0 (1.0.0)                                                   
ok   Installed fetch as github:github/fetch@^1.0.0 (1.0.0)                                                       
ok   Installed npm:aurelia-history@^1.0.0 (1.0.0)                                                                
ok   Installed npm:aurelia-task-queue@^1.0.0 (1.0.0)                                                             
ok   Installed npm:aurelia-loader@^1.0.0 (1.0.0)                                                                 
ok   Installed npm:aurelia-route-recognizer@^1.0.0 (1.0.0)                                                       
ok   Installed npm:aurelia-event-aggregator@^1.0.0 (1.0.0)                                                       
ok   Installed npm:aurelia-path@^1.0.0 (1.0.0)                                                                   
ok   Installed npm:aurelia-logging@^1.0.0 (1.0.0)                                                                
ok   Installed aurelia-logging-console as npm:aurelia-logging-console@^1.0.0-rc.1.0.0 (1.0.0)                    
ok   Installed npm:aurelia-metadata@^1.0.0 (1.0.0)                                                               
ok   Installed npm:aurelia-templating@^1.0.0 (1.0.0)                                                             
     Looking up npm:process                                                                                      
ok   Installed npm:aurelia-pal@^1.0.0 (1.0.0)                                                                    
ok   Installed aurelia-loader-default as npm:aurelia-loader-default@^1.0.0-rc.1.0.0 (1.0.0)                      
ok   Installed aurelia-history-browser as npm:aurelia-history-browser@^1.0.0-rc.1.0.0 (1.0.0)                    
ok   Installed aurelia-polyfills as npm:aurelia-polyfills@^1.0.0-rc.1.0.0 (1.0.0)                                
ok   Installed npm:aurelia-dependency-injection@^1.0.0 (1.0.0)                                                   
ok   Installed aurelia-router as npm:aurelia-router@^1.0.0-rc.1.0.0 (1.0.2)                                      
ok   Installed npm:aurelia-binding@^1.0.0 (1.0.0)                                                                
ok   Installed aurelia-framework as npm:aurelia-framework@^1.0.0-rc.1.0.0 (1.0.0)                                
ok   Installed aurelia-templating-resources as npm:aurelia-templating-resources@^1.0.0-rc.1.0.0 (1.0.0)          
ok   Installed aurelia-animator-css as npm:aurelia-animator-css@^1.0.0-rc.1.0.0 (1.0.0)                          
ok   Installed aurelia-templating-router as npm:aurelia-templating-router@^1.0.0-rc.1.0.0 (1.0.0)                
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.2)                                                       
ok   Installed github:systemjs/plugin-css@0.1 (0.1.25)                                                           
ok   Installed font-awesome as npm:font-awesome@4.6.3 (4.6.3)                                                    
ok   Installed npm:process@^0.11.0 (0.11.6)                                                                      
     Looking up github:jspm/nodelibs-fs                                                                          
     Looking up github:jspm/nodelibs-assert                                                                      
     Looking up github:jspm/nodelibs-vm                                                                          
ok   Installed npm:aurelia-pal-browser@^1.0.0 (1.0.0)                                                            
ok   Installed aurelia-pal-browser as npm:aurelia-pal-browser@^1.0.0-rc.1.0.0 (1.0.0)                            
ok   Installed npm:aurelia-templating-binding@^1.0.0 (1.0.0)                                                     
ok   Installed aurelia-templating-binding as npm:aurelia-templating-binding@^1.0.0-rc.1.0.0 (1.0.0)              
ok   Installed aurelia-bootstrapper as npm:aurelia-bootstrapper@^1.0.0-rc.1.0.0 (1.0.0)                          
     Looking up npm:assert                                                                                       
ok   Installed npm:jquery (2.2.4)                                                                                
ok   Installed jquery as npm:jquery@^2.2.4 (2.2.4)                                                               
ok   Installed bootstrap as github:twbs/bootstrap@^3.3.6 (3.3.7)                                                 
ok   Installed github:jspm/nodelibs-assert@^0.1.0 (0.1.0)                                                        
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)                                                            
     Looking up npm:util                                                                                         
ok   Installed npm:assert@^1.3.0 (1.4.1)                                                                         
     Looking up npm:inherits                                                                                     
ok   Installed npm:util@0.10.3 (0.10.3)                                                                          
     Looking up github:jspm/nodelibs-buffer                                                                      
ok   Installed npm:inherits@2.0.1 (2.0.1)                                                                        
     Looking up npm:vm-browserify                                                                                
ok   Installed github:jspm/nodelibs-vm@^0.1.0 (0.1.0)                                                            
     Looking up github:jspm/nodelibs-util                                                                        
     Looking up npm:indexof                                                                                      
ok   Installed npm:vm-browserify@0.0.4 (0.0.4)                                                                   
ok   Installed npm:indexof@0.0.1 (0.0.1)                                                                         
     Looking up npm:buffer                                                                                       
ok   Installed github:jspm/nodelibs-buffer@^0.1.0 (0.1.0)                                                        
     Looking up npm:base64-js                                                                                    
     Looking up npm:ieee754                                                                                      
     Looking up npm:isarray                                                                                      
ok   Installed npm:buffer@^3.0.1 (3.6.0)                                                                         
ok   Installed npm:isarray@^1.0.0 (1.0.0)                                                                        
ok   Installed github:jspm/nodelibs-util@^0.1.0 (0.1.0)                                                          
ok   Installed npm:base64-js@0.0.8 (0.0.8)                                                                       
     Looking up github:jspm/nodelibs-child_process                                                               
ok   Installed npm:ieee754@^1.1.4 (1.1.6)                                                                        
ok   Installed github:jspm/nodelibs-child_process@^0.1.0 (0.1.0)                                                 
ok   Installed bluebird as npm:bluebird@3.4.1 (3.4.1)                                                            
ok   Install tree has no forks.                                                                                  
     Looking up loader files...                                                                                  
       system.js                                                                                                 
       system.js.map                                                                                             
       system-csp-production.src.js                                                                              
       system.src.js                                                                                             
       system-csp-production.js.map                                                                              
       system-csp-production.js                                                                                  
       system-polyfills.js.map                                                                                   
       system-polyfills.src.js                                                                                   
       system-polyfills.js                                                                                       
                                                                                                                 
     Using loader versions:                                                                                      
       systemjs@0.19.37                                                                                          
ok   Loader files downloaded successfully                                                                        
```
`gukp watch`:

```
λ gulp watch                                                                                        
[10:29:20] Using gulpfile C:\work\skeletons\skeleton-navigation-1.0.0\skeleton-esnext\gulpfile.js   
[10:29:20] Starting 'build'...                                                                      
[10:29:20] Starting 'unbundle'...                                                                   
[10:29:20] Finished 'unbundle' after 29 ms                                                          
[10:29:20] Starting 'clean'...                                                                      
[10:29:20] Finished 'clean' after 14 ms                                                             
[10:29:20] Starting 'build-system'...                                                               
[10:29:20] Starting 'build-html'...                                                                 
[10:29:20] Starting 'build-css'...                                                                  
[10:29:20] Finished 'build-css' after 9.25 ms                                                       
[10:29:21] Finished 'build-html' after 1.52 s                                                       
[10:29:21] Finished 'build-system' after 1.56 s                                                     
[10:29:21] Finished 'build' after 1.61 s                                                            
[10:29:21] Starting 'serve'...                                                                      
[BS] Access URLs:                                                                                   
 ----------------------------                                                                       
 Local: http://localhost:9000                                                                       
 ----------------------------                                                                       
    UI: http://localhost:3001                                                                       
 ----------------------------                                                                       
[BS] Serving files from: .                                                                          
[10:29:24] Finished 'serve' after 2.42 s                                                            
[10:29:24] Starting 'watch'...                                                                      
[10:29:24] Finished 'watch' after 20 ms                                                             
```

**Comment by adriatic** [comment]
Here is the relevant section from the Monterey log

```
"info","npm-detection","2016-09-24T03:47:36.057Z","found package.json at C:\work\tests\Monterey-testing-09222016\skeleton-esnext\package.json"
"info","jspm-detection","2016-09-24T03:47:36.060Z","package.json has jspm section"
"info","jspm-detection","2016-09-24T03:47:36.060Z","jspm016Path: C:\work\tests\Monterey-testing-09222016\skeleton-esnext\config.js"
"info","jspm-detection","2016-09-24T03:47:36.060Z","jspm017Path: C:\work\tests\Monterey-testing-09222016\skeleton-esnext\jspm.config.js"
"info","aurelia-cli-detection","2016-09-24T03:47:36.061Z","did not find aurelia.json file"
"info","gulp-detection","2016-09-24T03:47:36.062Z","gulp file found: C:\work\tests\Monterey-testing-09222016\skeleton-esnext\gulpfile.js"
"info","gulp-detection","2016-09-24T03:47:36.063Z","gulp file found: C:\work\tests\Monterey-testing-09222016\skeleton-esnext\gulpfile.js"
"info","webpack-detection","2016-09-24T03:47:36.065Z","did not find webpack.config.js"
"info","typings-detection","2016-09-24T03:47:36.066Z","did not find typings.json file"
"info","dotnet-detection","2016-09-24T03:47:36.068Z","did not find project.json file"
"info","application-state","2016-09-24T03:47:36.108Z","State saved"
"info","project-manager","2016-09-24T03:47:36.112Z","Project added"
"info","application-state","2016-09-24T03:47:36.190Z","State saved"
"info","TaskManager","2016-09-24T03:47:52.322Z","queued 'NPM install' for project 'skeleton-esnext'"
"info","TaskManager","2016-09-24T03:47:52.324Z","queued 'JSPM install' for project 'skeleton-esnext'"
"info","TaskManager","2016-09-24T03:47:52.324Z","queued 'gulp watch' for project 'skeleton-esnext'"
"info","TaskManager","2016-09-24T03:47:52.324Z","started 'NPM install' for project 'skeleton-esnext'"
"info","PostCreate","2016-09-24T03:47:52.331Z","3 (NPM install, JSPM install, gulp watch) were checked"
"info","application-state","2016-09-24T03:47:52.430Z","State saved"
"info","TaskManager","2016-09-24T03:50:50.204Z","task 'NPM install' for project 'skeleton-esnext' finished without error"
"info","TaskManager","2016-09-24T03:50:50.208Z","started 'JSPM install' for project 'skeleton-esnext'"
"info","jspm-detection","2016-09-24T03:50:50.264Z","found jspm in this node_modules folder: C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm"
"info","TaskManager","2016-09-24T03:51:00.401Z","started 'gulp watch' for project 'skeleton-esnext'"
"info","TaskManager","2016-09-24T03:51:00.422Z","task 'JSPM install' for project 'skeleton-esnext' finished with error (after it ran for 10 seconds)"
"error","TaskManager","2016-09-24T03:51:00.422Z","Cannot read property 'object' of undefinedTypeError: Cannot read property 'object' of undefined    at ObjectsRegistry.get (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\objects-registry.js:44:28)    at EventEmitter.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\rpc-server.js:306:31)    at emitMany (events.js:127:13)    at EventEmitter.emit (events.js:201:7)    at WebContents.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\api\web-contents.js:219:13)    at emitTwo (events.js:106:13)    at WebContents.emit (events.js:191:7), Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'object' of undefined    at ObjectsRegistry.get (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\objects-registry.js:44:28)    at EventEmitter.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\rpc-server.js:306:31)    at emitMany (events.js:127:13)    at EventEmitter.emit (events.js:201:7)    at WebContents.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\browser\api\web-contents.js:219:13)    at emitTwo (events.js:106:13)    at WebContents.emit (events.js:191:7)    at metaToValue (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\renderer\api\remote.js:217:13)    at remoteMemberFunction (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\electron.asar\renderer\api\remote.js:111:18)    at EventEmitter.<anonymous> (C:\Users\nik\AppData\Local\monterey\app-0.4.2\resources\app.asar\jspm_packages\github\monterey-framework\monterey-pal-electron@0.1.47\jspm_commands.js:19:30)    at emitTwo (events.js:106:13)    at EventEmitter.emit (events.js:191:7)    at Object.exports.log (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\ui.js:89:24)    at logInstall (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\install.js:514:8)    at C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\jspm\lib\install.js:327:9    at tryCatch (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:538:12)    at invokeCallback (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:553:13)    at publish (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:521:7)    at MutationObserver.flush (C:\work\tests\Monterey-testing-09222016\skeleton-esnext\node_modules\rsvp\dist\rsvp.js:2370:5)    at process._tickCallback (internal/process/next_tick.js:103:7)"
"info","notification","2016-09-24T03:58:46.715Z","Copied error to clipboard"
"error","global exception","2016-09-24T04:01:13.886Z","Cannot read property 'stack' of undefined, TypeError: Cannot read property 'stack' of undefined    at e.text (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/dist/plugins/errors/error-modal.js:41:42)    at e.t [as onClick] (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9504)    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9276)    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:1175)"
"info","notification","2016-09-24T04:01:13.903Z","copied project information to clipboard"
"error","global exception","2016-09-24T04:02:03.053Z","Cannot read property 'stack' of undefined, TypeError: Cannot read property 'stack' of undefined    at e.text (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/dist/plugins/errors/error-modal.js:41:42)    at e.t [as onClick] (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9504)    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:9276)    at HTMLBodyElement.<anonymous> (file:///C:/Users/nik/AppData/Local/monterey/app-0.4.2/resources/app.asar/scripts/clipboard.min.js:7:1175)"
"info","notification","2016-09-24T04:02:03.060Z","copied project information to clipboard"
"info","notification","2016-09-24T04:02:03.068Z","Copied error to clipboard"
"info","TaskManager","2016-09-24T04:10:37.652Z","queued 'gulp watch' for project 'skeleton-esnext'"
"info","TaskManager","2016-09-24T04:10:37.652Z","started 'gulp watch' for project 'skeleton-esnext'"
"info","notification","2016-09-24T04:10:37.673Z","Started"
"info","TaskManager","2016-09-24T04:10:45.593Z","task 'gulp watch' for project 'skeleton-esnext' was cancelled by user"
"info","TaskManager","2016-09-24T04:10:45.731Z","task 'gulp watch' for project 'skeleton-esnext' finished without error"
"info","TaskManager","2016-09-24T04:16:01.579Z","task 'gulp watch' for project 'skeleton-esnext' was cancelled by user"
"info","TaskManager","2016-09-24T04:16:01.679Z","task 'gulp watch' for project 'skeleton-esnext' finished without error"
"info","application-state","2016-09-24T04:16:04.517Z","State saved"
```

**Comment by adriatic** [comment]
### Important:

This application can be built and executed on OSX, flawlessly. So, my next step is to reboot my Windows machine and try again
