### ISSUE TITLE
Error creating skeleton-typescript-aspnetcore

### ISSUE THREAD

**Issue by nialljt1** [monterey-framework/monterey#368]
### Intention
**I'm submitting a bug report**  

### Environment
* **Operating System:**
Windows 10

* **Node Version:**

* **NPM Version:**

### Description
I just installed monterey and tried to create a skeleton-typescript-aspnetcore and I got the following errors

[14:52:05] Error on lookup for `npm:aurelia-animator-css`
[14:52:05] Error: connect ETIMEDOUT 151.101.60.162:443
[14:52:05] at Object.exports._errnoException (util.js:1026:11)
[14:52:05] at exports._exceptionWithHostPort (util.js:1049:20)
[14:52:05] at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
[14:52:05] error while installing jspm packages,
[14:52:05] -----FINISHED WITH ERROR-----

**Expected/desired behavior:**  
To install without error

**What is the motivation / use case for changing the behavior?**  
To begin using monterey
### Logs
[2016-010-05.txt](https://github.com/monterey-framework/monterey/files/511345/2016-010-05.txt)

**Comment by JeroenVinke** [comment]
Hi @nialljt1 

Are you behind a proxy perhaps? If so, could you try https://jjasonclark.com/how-to-setup-node-behind-web-proxy ?

**Comment by nialljt1** [comment]
Hi Jerome,
Thanks for the suggestion. However,  I am just doing this from home. I am
not behind a proxy.
I will have a look again later.
Thanks
Niall
