### ISSUE TITLE
contact manager sample using materialize bridge fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#374]
### Intention

**I'm submitting a bug report**  

### Environment

* **Project name**
contact-manager-materialize
* **Project path:**
C:\work\tests\Monterey-testing-10062016\contact-manager-materialize
* **NodeJS:**
6.5.0
* **NPM:**
3.10.8
* **Electron:**
1.4.1
* **Chrome:**
53.0.2785.113
* **Operating system:**
win32

### Description

**Current behavior:**  
(SystemJS) Error: XHR error loading file:///C:/Users/nik/AppData/Local/monterey/app-0.4.4/resources/app.asar/dist/plugins/aurelia-cli/project-info.js Error loading file:///C:/Users/nik/AppData/Local/monterey/app-0.4.4/resources/app.asar/dist/plugins/aurelia-cli/project-info.js

**Stack trace from Chrome**

```
http://localhost:9000/scripts/materialize-bundle.css Failed to load resource: the server responded with a status of 404 (Not Found)
vendor-bundle.js:1399 Unhandled rejection Error: Failed loading required CSS file: aurelia-materialize-bridge/chip/chip.css
    at fixupCSSUrls (http://localhost:9000/scripts/vendor-bundle.js:23855:13)
    at http://localhost:9000/scripts/vendor-bundle.js:23894:16
From previous event:
    at CSSResource.load (http://localhost:9000/scripts/vendor-bundle.js:23893:10)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:19508:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:19457:37)
    at http://localhost:9000/scripts/vendor-bundle.js:19818:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:19787:52)
    at ViewEngine.loadTemplateResources (http://localhost:9000/scripts/vendor-bundle.js:19757:19)
    at http://localhost:9000/scripts/vendor-bundle.js:19705:41
From previous event:
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19689:67)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:17109:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:20447:29)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:19508:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:19450:25)
    at http://localhost:9000/scripts/vendor-bundle.js:19818:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:19787:52)
    at http://localhost:9000/scripts/vendor-bundle.js:11282:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:11273:9)
    at http://localhost:9000/scripts/vendor-bundle.js:11350:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:11230:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:11236:12)
    at http://localhost:9000/scripts/vendor-bundle.js:11515:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:11514:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:11499:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:11116:23)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:218:13)
    at http://localhost:9000/scripts/vendor-bundle.js:10454:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:10453:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:10444:12)
    at http://localhost:9000/scripts/vendor-bundle.js:10473:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:10471:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:10470:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:10466:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:10493:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3785:299)
    at Object.check (http://localhost:9000/scripts/vendor-bundle.js:3774:50)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3779:58)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3783:433)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:3778:436)
    at http://localhost:9000/scripts/vendor-bundle.js:3763:140
    at y (http://localhost:9000/scripts/vendor-bundle.js:3762:207)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3777:469)
    at Object.init (http://localhost:9000/scripts/vendor-bundle.js:3772:154)
    at http://localhost:9000/scripts/vendor-bundle.js:3782:308
```

**Comment by Thanood** [comment]
There are some strange things going on right now.
A bridge user confirmed not needing that large `resources` array anymore (defining all html and css files). It's confirmed in three projects and I can run his project, too.

Anyway with the sample, it's just not happening somehow. Trying a new au-cli project now (after upgrading), maybe something is different in the cli itself or its build scripts.

**Comment by JeroenVinke** [comment]
continuing in https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/293#issuecomment-252385802

**Comment by Thanood** [comment]
Fixed for this app.
The discussions mentioned above by @JeroenVinke is still valid.
