### ISSUE TITLE
check dependencies first

### ISSUE THREAD

**Issue by TheJJJ** [monterey-framework/monterey#386]
**I'm submitting a bug report**  

### Environment
* **Operating System:** 
Win7-64

* **Node Version:** 
current

* **NPM Version:** 
current

### Description
**Current behavior:**  
during monterey doing it´s scaffolding magic there was a alert message (top right corner) that some node help stuff wasn´t installed. It was good that the node command was provided! I did install it and ran the magic a second time to make sure everything is ok.

**Expected/desired behavior:**  

1) monterey should check the dependencies first
2) i didn´t know if this error caused further trouble or was allready fixed by installing the dependency. a hint would be useful.

**Comment by adriatic** [comment]
@TheJJJ Can you please let us know the Monterey version number (is is displayed on the About page, accessible via About button on the toolbar in the footer area.

`some node help stuff wasn´t installed` is not very helpful, can you be more precise?

I am also not sure what you meant with `the node command was provided` - please elaborate.

Lastly: Monterey keeps a log of its actions as described here

![image](https://cloud.githubusercontent.com/assets/2712405/19367073/a174ea78-9167-11e6-9973-fdc657167e8a.png)

Please add the .txt file that was created at the time you had your problems (you can determine which one by matching its creation date with the time you used Monterey) and add it to this problem report

**Comment by TheJJJ** [comment]
Hi adriatic,

thank you for your precise documentation. I wouldn´t have found it so easily by myself.

Monterey version: 0.4.7
NodeJS version: 6.5.0
Electron version: 1.4.1

"error","notification","2016-10-13T15:11:25.719Z","Error during "au help". Did you install aurelia-cli? npm install aurelia-cli -g"

"error","aurelia-cli-plugin","2016-10-13T15:11:25.720Z","Command failed: au helpDer Befehl "au" ist entweder falsch geschrieben oderkonnte nicht gefunden werden., Error: Command failed: au helpDer Befehl "au" ist entweder falsch geschrieben oderkonnte nicht gefunden werden.    at ChildProcess.exithandler (child_process.js:218:12)    at emitTwo (events.js:106:13)    at ChildProcess.emit (events.js:191:7)    at maybeClose (internal/child_process.js:877:16)    at Socket.<anonymous> (internal/child_process.js:334:11)    at emitOne (events.js:96:13)    at Socket.emit (events.js:188:7)    at Pipe._handle.close [as _onclose] (net.js:493:12)"

the german sentence in english:
 The command "au" is either wrong or could not be found.

**Comment by adriatic** [comment]
I believe that it is very easy to help you in this situation - all you need to do is to open the console and type `npm install aurelia-cli -g`. This will add the [aurelia-cli component](https://github.com/aurelia/cli) to your computer, and consequently allow monterey to use it in some of application creation scenarios that depend on aurelia-cli being installed

See
1. [Creating new application / Aurelia-CLI](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/aurelia-cli.html) and its three sub-sections.
2. [Creating new application / GitHub](https://aurelia-ui-toolkits.gitbooks.io/monterey-user-manual/content/creating_new_application/github.html) and its subsections.

for more information on Aurelia-CLI application creation.

**Comment by TheJJJ** [comment]
My intention wasn´t to complain that the npm command was impossible for me (as I wrote: 'i dit it'), but to give a hint where monterey might be improved. Either:
- let monterey check for missing dependencies first and give the user the hint and command to fix it upfront,
- let monterey install missing dependencies,
- tell the user that the npm command afterwards will fix any problems or if the scaffolding has to be repeated. 

Thank you all for your engagement for good software.

**Comment by Thanood** [comment]
@TheJJJ This is discussed, among other things, in the "sanity check" issue #365 . :smiley: 
In my opinion an existing installation of `aurelia-cli` should be checked before anything else, so I agree.

We've also discussed whether we could just run `npm i -g aurelia-cli` from Monterey but we dropped that because this would mean gaining administrator privileges (at least on a unix based system).

**Comment by adriatic** [comment]
> My intention wasn´t to complain that the npm command was impossible for me (as I wrote: 'i dit it'), but to give a hint where monterey might be improved

@TheJJJ - your intent is clearly understood and much appreciated 😏
