### ISSUE TITLE
Building Monterey on Windows 8.1 fails

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#413]
### Intention

**I'm submitting a bug report**  

### Environment

* **Operating System:**  Windows 8.1

* **Node Version:**  6.3.1

* **NPM Version:**  3.4.0

### Description
**Current behavior:**  

After successul execution of `npm install --global --production windows-build-tools npm@next`, the command `npm run setup fails`

```
λ npm run setup

> monterey@0.4.7 setup C:\Work\monterey-framework\monterey
> node utils -setup && node utils -rebuild-native

running NPM -> main

> nslog@3.0.0 install C:\Work\monterey-framework\monterey\node_modules\nslog
> node-gyp rebuild


C:\Work\monterey-framework\monterey\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Work\monterey-framework\monterey\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error  MSB6006: "CL.exe" exited with code -1073741515. [C:\Work\monterey-framework\monterey\node_modul es\nslog\build\nslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Work\monterey-framework\monterey\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Work\\monterey-framework\\monterey\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Work\monterey-framework\monterey\node_modules\nslog
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
monterey@0.4.7 C:\Work\monterey-framework\monterey
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.5 (node_modules\electron-builder\node_modules\appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-osx@^1.0.0 (node_modules\7zip-bin\node_modules\7zip-bin-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Work\\monterey-framework\\monterey\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\monterey-framework\monterey\npm-debug.log
npm ERR! code 1
Failed: 1
module.js:442
    throw err;
    ^

Error: Cannot find module 'electron-rebuild'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at rebuildNative (C:\Work\monterey-framework\monterey\utils.js:10:28)
    at Object.<anonymous> (C:\Work\monterey-framework\monterey\utils.js:134:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nikolaj\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.3.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! monterey@0.4.7 setup: `node utils -setup && node utils -rebuild-native`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the monterey@0.4.7 setup script 'node utils -setup && node utils -rebuild-native'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the monterey package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node utils -setup && node utils -rebuild-native
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs monterey
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls monterey
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\monterey-framework\monterey\npm-debug.log
```

[npm-debug.log.txt](https://github.com/monterey-framework/monterey/files/614381/npm-debug.log.txt)

**Comment by JeroenVinke** [comment]
> Cannot find module 'electron-rebuild'

This indicates that `npm install` has not been successfully executed

>  error enoent ENOENT: no such file or directory, open 'C:\Work\monterey-framework\package.json'

Doesn't this need to be executed from `C:\Work\monterey-framework\monterey` ?

**Comment by JeroenVinke** [comment]
node-gyp has been removed, so I expect this to be solved
