### ISSUE TITLE
How to learn programming Monterey

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#419]
### Intention

**I'm submitting a discussion request**  

### Definition 

I was recently discussing with Jeroen my problem related to making a changes to Monterey that are more involved than editing an existing page (I am quite good at that by the way :smirk:. A good example is the discussion in the article **application template chooser (ATC) wizard's page** (https://github.com/monterey-framework/monterey/issues/416), which leads to reuse of concept of  Monterey tiles

<p align="center">
 <img src="https://cloud.githubusercontent.com/assets/2712405/20894738/9a9c69be-bae4-11e6-9b83-c9a98bbd3a58.png"/>
<p>

in a completely different context: selectors for application skeleton types in the new app creation wizard

![image](https://cloud.githubusercontent.com/assets/2712405/20895385/3ee313f4-bae7-11e6-97b8-44373c5ae313.png)

This task is too involved to take on with my current experience with Monterey - and Jeroen's response was right on:

> Since we have not added a whole lot of features yet, there are not many examples for you to learn from. I understand that this is difficult, and I think that you should "bother" me more often. This goes for documentation as well. 

### Here is my proposal

Until any new Monterey team member graduates "Monterey app development curriculum", he/she might find it easier to develop new Monterey pieces as Aurelia Web applications starting with **[this skeleton](https://github.com/aurelia-ui-toolkits/kendoui-tutorials-code/tree/master/skeleton-esnext)**, which I will gradually enhance to be a lot closer to Monterey's "general shape". 

Using the above described problem as the example, I could completely create the **`Application template chooser (ATC) custom element`** without spending any time worrying about how to stuff it in Monterey. The issue of creation of the `selectors for application skeleton types ` can be easily solved by faking them (providing the correct icons, shapes, etc) and once this is done, I simply pass it to Jeroen to do the integration.

In order to save all the know-how to for others, I would **document** the creation of my parts that stay in Monterey unchanged and Jeroen will **document** the work he needed to do in order to integrate such new component.

All these documents should be kept in the **[Monterey developer manual](https://aurelia-ui-toolkits.gitbooks.io/monterey-developer-manual/content/)**

**Comment by adriatic** [comment]
Assuming that this is something we can all agree on, I need a bit of help with one details: I can run **[this sample](https://github.com/aurelia-ui-toolkits/kendoui-tutorials-code/tree/master/skeleton-esnext)** without a hitch using the commands

```
npm install
jspm install
gulp watch
```

![image](https://cloud.githubusercontent.com/assets/2712405/20896243/c0e99f32-baea-11e6-9312-93fab9287d1b.png)

However using **[these instructions](https://github.com/aurelia-ui-toolkits/kendoui-tutorials-code/blob/master/skeleton-esnext/README.md#running-the-app-under-electron)** I get 

```
Uncaught ReferenceError: jQuery is not defined
bluebird.min.js:33 Error: (SystemJS) Bootstrap's JavaScript requires jQuery
	Error: Bootstrap's JavaScript requires jQuery
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7/js/bootstrap.js:12:9
	    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
	    at Object.exports.runInThisContext (vm.js:77:17)
	    at Object.<anonymous> (file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:1:123)
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:2:4
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:3:3
	    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
	    at Object.exports.runInThisContext (vm.js:77:17)
	Evaluating file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7/js/bootstrap.js
	Evaluating file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js
	Error loading file:///C:/work/monterey-framework/prototyping/skeleton/dist/main.js
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7/js/bootstrap.js:12:9
	    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
	    at Object.exports.runInThisContext (vm.js:77:17)
	    at Object.<anonymous> (file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:1:123)
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:2:4
	    at file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js:3:3
	    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
	    at Object.exports.runInThisContext (vm.js:77:17)
	Evaluating file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7/js/bootstrap.js
	Evaluating file:///C:/work/monterey-framework/prototyping/skeleton/jspm_packages/github/twbs/bootstrap@3.3.7.js
	Error loading file:///C:/work/monterey-framework/prototyping/skeleton/dist/main.jsr @ bluebird.min.js:33
```

Clearly, jQuery is there (as KendoUI bridge is using it when run as a web app), so this is something related to Electron that I am missing.

**Comment by JeroenVinke** [comment]
Yes, I remember this issue. When jQuery is loaded into a jQuery environment it does not attach the `$` or `jQuery` global to the window object. The solution is mentioned in https://github.com/electron/electron/issues/254#issuecomment-190950945. I have pushed this change in [this commit](https://github.com/aurelia-ui-toolkits/kendoui-tutorials-code/commit/0d64764923f579fc98ecc6e3199d24915ee569af)

**Comment by adriatic** [comment]
Thanks - very easy solution, once the problem is understood (what is different between the electron and browserify context).

You had not comments to my concept explained above? It involves your participation in documenting stuff :-)

**Comment by JeroenVinke** [comment]
I notice that it's trying to load the resource using the `file:///` protocol and not the `http://` protocol

You are probably using `'//demos.telerik.com/kendo-ui/service/Northwind.svc/Customers'` as the URL in the datasource. Which is fine when the application is run from the browser (since you load webpages from the http:// protocol), but when an application is run from electron the `file:///` protocol is used.

Try and change `'//demos.telerik.com/kendo-ui/service/Northwind.svc/Customers'` to `https://demos.telerik.com/kendo-ui/service/Northwind.svc/Customers'`

**Comment by JeroenVinke** [comment]
> You had no comments to my concept explained above? It involves your participation in documenting stuff :-)

The risky thing is that you will not be working from Monterey, and therefore will not be exposing what's not documented enough. But despite that, I am fine with this approach

**Comment by adriatic** [comment]
Good observation. I will use my proposed indirect approach only in "extreme cases", where just the fact that I am using it will indicate where we need better documentation or when I do not feel "safe" to make sweeping changes and would prefer that you integrate my code. application template chooser (ATC) wizard's page (https://github.com/monterey-framework/monterey/issues/416) is a good example of such situation.

**Comment by JeroenVinke** [comment]
Sounds like a much better approach, yes

**Comment by adriatic** [comment]
For example - I am about to start writing the code for **[Monterey Package Chooser (MPC) - aurelia-cli tool version](https://github.com/monterey-framework/monterey/issues/415)** directly in "my" current branch of Monterey, trying to reach the point where we could use Monterey to test the initial version of `aurelia-cli importer` tool
