### ISSUE TITLE
Testing scaffold test

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/monterey#429]
### Intention

**I'm submitting a bug report**

**Comment by adriatic** [comment]
### Error: create is not a function(…)

```
INFO [launcher-manager] img path: C:\Users\nik\AppData\Roaming\monterey/images/app-launcher/win32/chrome.png
aurelia-logging-console.js:34 INFO [application-state] State saved
global-exception-handler.ts:15 Error: create is not a function(…)
aurelia-logging-console.js:54 ERROR [global exception] Error: create is not a function(…)error @ aurelia-logging-console.js:54
aurelia-binding.js:1974 Uncaught Error: create is not a function
global-exception-handler.ts:15 Error: create is not a function
    at getFunction (file:///H:/work/monterey/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.4/aurelia-binding.js:1974:11)
    at CallScope.evaluate (file:///H:/work/monterey/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.4/aurelia-binding.js:1568:18)
    at Listener.callSource (file:///H:/work/monterey/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.4/aurelia-binding.js:5011:42)
    at file:///H:/work/monterey/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.4/aurelia-binding.js:5035:24
    at HTMLDocument.handleDelegatedEvent (file:///H:/work/monterey/monterey-framework/monterey/app/jspm_packages/npm/aurelia-binding@1.0.4/aurelia-binding.js:3224:11)
aurelia-logging-console.js:54 ERROR [global exception] Error: create is not a function(…)error @ aurelia-logging-console.js:54
aurelia-binding.js:1974 Uncaught Error: create is not a function
```

**Comment by JeroenVinke** [comment]
Ah you are clicking the create button when monterey started for the very first time. Try adding an existing application and then click the create button on the main screen instead.

**Comment by JeroenVinke** [comment]
I disabled that button you are clicking on in order to quickly silence the error it threw

**Comment by adriatic** [comment]
Knowing you, this explanation does not make complete sense. Clearly, your suggestion is a workaround - not a feature, so I wonder why is it that you simply do not fix this bug (note, I am asking you for the reason why not fixing it - not to fix it)

**Comment by JeroenVinke** [comment]
That is because what I asked you to look at is a prototype, thus not perfect so we can easily throw it away

**Comment by adriatic** [comment]
**That** does make sense
